// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };

// module.exports = sidebars;

module.exports = {
  mySidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: '━ Features ━',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Features/effort-calculator',
        },
        {
          type: 'doc',
          id: 'Features/frame-tester',
        },
        {
          type: 'doc',
          id: 'Features/multiframe-tester',
        },
        {
          type: 'doc',
          id: 'Features/morph-tester',
          label: "Morph Tester"
        },
        {
          type: 'doc',
          id: 'Features/trace',
          label: "Card Tracer"
        },
        {
          type: 'doc',
          id: 'Features/bits-calculator',
        },
        {
          type: 'doc',
          id: 'Features/card-codes-generator',
        },
        {
          type: 'doc',
          id: 'Features/koibito-finder',
        },
        {
          type: 'doc',
          id: 'Features/not-starboard',
        },
        {
          type: 'doc',
          id: 'Features/server-drop-ping',
        },
        {
          type: 'doc',
          id: 'Features/wishlist-notifier',
        },
        {
          type: 'doc',
          id: 'Features/Global Market',
        },
        {
          type: 'doc',
          id: 'Features/price-calc',
          label: "Price Calculator"
        },
      ],
    },
    // {
    //   type: 'link',
    //   label: 'Learn more',
    //   href: 'https://example.com',
    // },
  ],
};


